apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}
  namespace: argocd
  labels:
    app: ${{ values.name }}
    managed-by: backstage
spec:
  project: idp-apps
  source:
    repoURL: https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
